### ISSUE TITLE
World can't create when Mob Drops = Null

### ISSUE THREAD

**Issue by squirrelkiller** [Xilef11/runesofwizardry-classics#2]
So it turns out if mob drops are null for a mod added mob, then the world gets stuck. It won't crash but it won't ever continue either. This lead to a latest.log being over 30 MB large.

A 30MB large text file. I just want to say the largest text file I have ever seen was a single class game I made in highschool to see if I could do it. Just saying, Java doesn't like you building an entire RPG in one single class file. Even then it was only 40MB

Back on topic, have the first 126 lines of the latest.log:

```
[02:55:48] [Client thread/INFO]: Setting user: squirrel_killer
[02:55:52] [Client thread/INFO]: LWJGL Version: 2.9.4
[02:56:03] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:AbyssalCraft Integration, FMLFileResourcePack:AbyssalCraft, FMLFileResourcePack:Aura Cascade, FMLFileResourcePack:Bagginses, FMLFileResourcePack:Baubles, FMLFileResourcePack:Baubles Stuff, FMLFileResourcePack:Better Achievements, FMLFileResourcePack:Better Builder's Wands, FMLFileResourcePack:Biomes O' Plenty, FMLFileResourcePack:Blood Magic: Alchemical Wizardry, FMLFileResourcePack:Bookshelf, FMLFileResourcePack:Bookshelf, FMLFileResourcePack:Chameleon, FMLFileResourcePack:Chickens, FMLFileResourcePack:Chisels & Bits, FMLFileResourcePack:ColorChat, FMLFileResourcePack:Cooking for Blockheads, FMLFileResourcePack:Cyclops Core, FMLFileResourcePack:Enchanting Plus, FMLFileResourcePack:EvilCraft, FMLFileResourcePack:Extra Bit Manipulation, FMLFileResourcePack:Fast Leaf Decay, FMLFileResourcePack:FlatBedrock Xplosion's Edition, FMLFileResourcePack:Hopper Ducts, FMLFileResourcePack:Integrated Dynamics, FMLFileResourcePack:Simple Inventory sorting, FMLFileResourcePack:Iron Chest, FMLFileResourcePack:Just Enough Items, FMLFileResourcePack:JourneyMap, FMLFileResourcePack:Just Enough Resources, FMLFileResourcePack:K4Lib, FMLFileResourcePack:MCMultiPart, FMLFileResourcePack:MoreOverlays, FMLFileResourcePack:Morpheus, FMLFileResourcePack:NeoTech, FMLFileResourcePack:No Mob Spawning on Trees, FMLFileResourcePack:NoMoreRecipeConflict, FMLFileResourcePack:Pam's HarvestCraft, FMLFileResourcePack:Progressive Automation, FMLFileResourcePack:Psi, FMLFileResourcePack:PVP Toggle, FMLFileResourcePack:QuantumFlux, FMLFileResourcePack:Quark, FMLFileResourcePack:Random Things, FMLFileResourcePack:RebornCore, FMLFileResourcePack:Redstone Paste, FMLFileResourcePack:Reliquary, FMLFileResourcePack:RFTools, FMLFileResourcePack:Router Reborn, FMLFileResourcePack:Runes of Wizardry, FMLFileResourcePack:Runes of Wizardry - Classic Dusts Pack, FMLFileResourcePack:Silent Lib, FMLFileResourcePack:Silent's Gems, FMLFileResourcePack:SK Utilities, FMLFileResourcePack:Storage Drawers, FMLFileResourcePack:TechReborn, FMLFileResourcePack:TSON Craft, FMLFileResourcePack:Vein Miner, FMLFileResourcePack:Mod Support, FMLFileResourcePack:Waila, FMLFileResourcePack:WAILA-features, FMLFileResourcePack:Waila Harvestability, FMLFileResourcePack:Wuest Utilities
[02:56:51] [Sound Library Loader/INFO]: Starting up SoundSystem...
[02:56:51] [Thread-14/INFO]: Initializing LWJGL OpenAL
[02:56:51] [Thread-14/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[02:56:51] [Thread-14/INFO]: OpenAL initialized.
[02:56:51] [Sound Library Loader/INFO]: Sound engine started
[02:56:57] [Client thread/INFO]: Created: 16x16 textures-atlas
[02:57:47] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:AbyssalCraft Integration, FMLFileResourcePack:AbyssalCraft, FMLFileResourcePack:Aura Cascade, FMLFileResourcePack:Bagginses, FMLFileResourcePack:Baubles, FMLFileResourcePack:Baubles Stuff, FMLFileResourcePack:Better Achievements, FMLFileResourcePack:Better Builder's Wands, FMLFileResourcePack:Biomes O' Plenty, FMLFileResourcePack:Blood Magic: Alchemical Wizardry, FMLFileResourcePack:Bookshelf, FMLFileResourcePack:Bookshelf, FMLFileResourcePack:Chameleon, FMLFileResourcePack:Chickens, FMLFileResourcePack:Chisels & Bits, FMLFileResourcePack:ColorChat, FMLFileResourcePack:Cooking for Blockheads, FMLFileResourcePack:Cyclops Core, FMLFileResourcePack:Enchanting Plus, FMLFileResourcePack:EvilCraft, FMLFileResourcePack:Extra Bit Manipulation, FMLFileResourcePack:Fast Leaf Decay, FMLFileResourcePack:FlatBedrock Xplosion's Edition, FMLFileResourcePack:Hopper Ducts, FMLFileResourcePack:Integrated Dynamics, FMLFileResourcePack:Simple Inventory sorting, FMLFileResourcePack:Iron Chest, FMLFileResourcePack:Just Enough Items, FMLFileResourcePack:JourneyMap, FMLFileResourcePack:Just Enough Resources, FMLFileResourcePack:K4Lib, FMLFileResourcePack:MCMultiPart, FMLFileResourcePack:MoreOverlays, FMLFileResourcePack:Morpheus, FMLFileResourcePack:NeoTech, FMLFileResourcePack:No Mob Spawning on Trees, FMLFileResourcePack:NoMoreRecipeConflict, FMLFileResourcePack:Pam's HarvestCraft, FMLFileResourcePack:Progressive Automation, FMLFileResourcePack:Psi, FMLFileResourcePack:PVP Toggle, FMLFileResourcePack:QuantumFlux, FMLFileResourcePack:Quark, FMLFileResourcePack:Random Things, FMLFileResourcePack:RebornCore, FMLFileResourcePack:Redstone Paste, FMLFileResourcePack:Reliquary, FMLFileResourcePack:RFTools, FMLFileResourcePack:Router Reborn, FMLFileResourcePack:Runes of Wizardry, FMLFileResourcePack:Runes of Wizardry - Classic Dusts Pack, FMLFileResourcePack:Silent Lib, FMLFileResourcePack:Silent's Gems, FMLFileResourcePack:SK Utilities, FMLFileResourcePack:Storage Drawers, FMLFileResourcePack:TechReborn, FMLFileResourcePack:TSON Craft, FMLFileResourcePack:Vein Miner, FMLFileResourcePack:Mod Support, FMLFileResourcePack:Waila, FMLFileResourcePack:WAILA Features, FMLFileResourcePack:Waila Harvestability, FMLFileResourcePack:Wuest Utilities
[02:58:20] [Client thread/INFO]: SoundSystem shutting down...
[02:58:20] [Client thread/WARN]: Author: Paul Lamb, www.paulscode.com
[02:58:20] [Sound Library Loader/INFO]: Starting up SoundSystem...
[02:58:20] [Thread-20/INFO]: Initializing LWJGL OpenAL
[02:58:20] [Thread-20/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[02:58:20] [Thread-20/INFO]: OpenAL initialized.
[02:58:21] [Sound Library Loader/INFO]: Sound engine started
[02:58:29] [Client thread/WARN]: Texture skutilities:textures/items/ironNugget.png with size 100x100 limits mip level from 4 to 2
[02:58:30] [Client thread/WARN]: textures: dropping miplevel from 4 to 2, because of minimum power of two: 4
[02:58:31] [Client thread/INFO]: Created: 4096x4096 textures-atlas
[03:00:03] [Client thread/INFO]: Deleting level New World
[03:00:03] [Client thread/INFO]: Attempt 1...
[03:00:12] [Server thread/INFO]: Starting integrated minecraft server version 1.9
[03:00:12] [Server thread/INFO]: Generating keypair
[03:00:12] [Server thread/WARN]: Unable to find spawn biome
[03:00:15] [Server thread/INFO]: Preparing start region for level 0
[03:00:16] [Server thread/INFO]: Preparing spawn area: 6%
[03:00:17] [Server thread/INFO]: Preparing spawn area: 10%
[03:00:18] [Server thread/INFO]: Preparing spawn area: 15%
[03:00:19] [Server thread/INFO]: Preparing spawn area: 20%
[03:00:20] [Server thread/INFO]: Preparing spawn area: 25%
[03:00:21] [Server thread/INFO]: Preparing spawn area: 30%
[03:00:22] [Server thread/INFO]: Preparing spawn area: 36%
[03:00:23] [Server thread/INFO]: Preparing spawn area: 41%
[03:00:24] [Server thread/INFO]: Preparing spawn area: 46%
[03:00:25] [Server thread/INFO]: Preparing spawn area: 49%
[03:00:26] [Server thread/INFO]: Preparing spawn area: 55%
[03:00:27] [Server thread/INFO]: Preparing spawn area: 61%
[03:00:28] [Server thread/INFO]: Preparing spawn area: 66%
[03:00:29] [Server thread/INFO]: Preparing spawn area: 74%
[03:00:30] [Server thread/INFO]: Preparing spawn area: 77%
[03:00:31] [Server thread/INFO]: Preparing spawn area: 82%
[03:00:32] [Server thread/INFO]: Preparing spawn area: 88%
[03:00:33] [Server thread/INFO]: Preparing spawn area: 94%
[03:00:34] [Server thread/INFO]: Preparing spawn area: 96%
[03:00:36] [Server thread/INFO]: Changing view distance to 12, from 10
[03:00:38] [Server thread/INFO]: squirrel_killer[local:E:c03225e0] logged in with entity id 4276 at (-82.5, 72.0, 128.5)
[03:00:38] [Server thread/INFO]: §csquirrel_killer joined the game
[03:00:39] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [g.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1041) [bcf.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:366) [bcf.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at org.cyclops.evilcraft.entity.monster.VengeanceSpirit.isEnabledVengeance(VengeanceSpirit.java:453) ~[VengeanceSpirit.class:?]
	at org.cyclops.evilcraft.entity.monster.VengeanceSpirit.isClientVisible(VengeanceSpirit.java:403) ~[VengeanceSpirit.class:?]
	at org.cyclops.evilcraft.entity.monster.VengeanceSpirit.isVisible(VengeanceSpirit.java:397) ~[VengeanceSpirit.class:?]
	at org.cyclops.evilcraft.entity.monster.VengeanceSpirit.func_70106_y(VengeanceSpirit.java:278) ~[VengeanceSpirit.class:?]
	at xilef11.mc.runesofwizardry_classics.runes.RuneResurrection.initDropsTable(RuneResurrection.java:111) ~[RuneResurrection.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_271_RuneResurrection_initDropsTable_Load.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
	at net.minecraft.client.multiplayer.WorldClient.<init>(WorldClient.java:72) ~[bku.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.func_147282_a(NetHandlerPlayClient.java:270) ~[bks.class:?]
	at net.minecraft.network.play.server.SPacketJoinGame.func_148833_a(SourceFile:76) ~[gs.class:?]
	at net.minecraft.network.play.server.SPacketJoinGame.func_148833_a(SourceFile:13) ~[gs.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fh$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[g.class:?]
	... 9 more
[03:00:39] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [g.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1041) [bcf.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:366) [bcf.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.client.network.NetHandlerPlayClient.func_147240_a(NetHandlerPlayClient.java:1751) ~[bks.class:?]
	at net.minecraft.network.play.server.SPacketCustomPayload.func_148833_a(SPacketCustomPayload.java:58) ~[gh.class:?]
	at net.minecraft.network.play.server.SPacketCustomPayload.func_148833_a(SPacketCustomPayload.java:11) ~[gh.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fh$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[g.class:?]
	... 9 more
[03:00:39] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [g.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1041) [bcf.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:366) [bcf.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.client.network.NetHandlerPlayClient.func_175101_a(NetHandlerPlayClient.java:1421) ~[bks.class:?]
	at net.minecraft.network.play.server.SPacketServerDifficulty.func_148833_a(SourceFile:25) ~[fw.class:?]
	at net.minecraft.network.play.server.SPacketServerDifficulty.func_148833_a(SourceFile:9) ~[fw.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fh$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[g.class:?]
	... 9 more
```

Turns out pastebinning almost 400000 lines of text breaks pastebin. So I have to dropbox the Latest.log

https://www.dropbox.com/s/0cwe1aq3d8rv3fg/latest.log?dl=1

Sorry, I feel so bad reporting thing one.

**Comment by rubensworks** [comment]
I don't think this mod is doing anything wrong, I'll fix it on EvilCraft's end.

**Comment by Xilef11** [comment]
looks like one of the drops has a null item in a non-null ItemStack... I'll add a safety check because I saw similar issues in other mods, but that is not something people should be doing

**Comment by Xilef11** [comment]
v1.9-0.3.1 and v1.8.9-0.2.1 should be safer about the null drops
