### ISSUE TITLE
Rune of Lumber crash on 1.11.2-0.5.1

### ISSUE THREAD

**Issue by TheFurtivePygmy** [Xilef11/runesofwizardry-classics#9]
Crashes when the rune is activated, and subsequently on world load.

```
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 8/10/17 5:54 PM
Description: Ticking block entity

java.lang.IllegalArgumentException: Stack can not be invalid!
	at net.minecraftforge.oredict.OreDictionary.getOreIDs(OreDictionary.java:440)
	at com.zpig333.runesofwizardry.util.Utils.stacksEqualWildcardSize(Utils.java:82)
	at xilef11.mc.runesofwizardry_classics.runes.entity.RuneEntityLumber.isWood(RuneEntityLumber.java:174)
	at xilef11.mc.runesofwizardry_classics.runes.entity.RuneEntityLumber.update(RuneEntityLumber.java:68)
	at com.zpig333.runesofwizardry.tileentity.TileEntityDustActive.func_73660_a(TileEntityDustActive.java:80)
	at net.minecraft.world.World.func_72939_s(World.java:1802)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraftforge.oredict.OreDictionary.getOreIDs(OreDictionary.java:440)
	at com.zpig333.runesofwizardry.util.Utils.stacksEqualWildcardSize(Utils.java:82)
	at xilef11.mc.runesofwizardry_classics.runes.entity.RuneEntityLumber.isWood(RuneEntityLumber.java:174)
	at xilef11.mc.runesofwizardry_classics.runes.entity.RuneEntityLumber.update(RuneEntityLumber.java:68)
	at com.zpig333.runesofwizardry.tileentity.TileEntityDustActive.func_73660_a(TileEntityDustActive.java:80)

-- Block entity being ticked --
Details:
	Name: minecraft:te_dust_active // com.zpig333.runesofwizardry.tileentity.TileEntityDustActive
	Block type: ID #237 (tile.runesofwizardry_dust_placed // com.zpig333.runesofwizardry.block.BlockDustPlaced)
	Block data value: 1 / 0x1 / 0b0001
	Block location: World: (594,4,-622), Chunk: (at 2,0,2 in 37,-39; contains blocks 592,0,-624 to 607,255,-609), Region: (1,-2; contains chunks 32,-64 to 63,-33, blocks 512,0,-1024 to 1023,255,-513)
	Actual block type: ID #237 (tile.runesofwizardry_dust_placed // com.zpig333.runesofwizardry.block.BlockDustPlaced)
	Actual block data value: 1 / 0x1 / 0b0001
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1802)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)

-- Affected level --
Details:
	Level name: Test
	All players: 1 total; [EntityPlayerMP['Dokidoki'/0, l='Test', x=594.60, y=4.00, z=-625.69]]
	Chunk stats: ServerChunkCache: 625 Drop: 0
	Level seed: 8010502870956864989
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (596,4,-628), Chunk: (at 4,0,12 in 37,-40; contains blocks 592,0,-640 to 607,255,-625), Region: (1,-2; contains chunks 32,-64 to 63,-33, blocks 512,0,-1024 to 1023,255,-513)
	Level time: 19020 game time, 5171 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 513 (now: false), thunder time: 57806 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_141, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1547945464 bytes (1476 MB) / 2112618496 bytes (2014 MB) up to 2112618496 bytes (2014 MB)
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms2G -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSParallelRemarkEnabled
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.38 Powered by Forge 13.20.1.2429 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.1.2429.jar) 
	UCHIJAAAA	forge{13.20.1.2429} [Minecraft Forge] (forge-1.11.2-13.20.1.2429.jar) 
	UCHIJAAAA	runesofwizardry{1.11.2-0.8.2} [Runes of Wizardry] (Runes-of-Wizardry-1.11.2-0.8.2.jar) 
	UCHIJAAAA	runesofwizardry_classics{1.11.2-0.5.1} [Runes of Wizardry - Classic Dusts Pack] (RunesofWizardry-Classics-1.11.2-0.5.1.jar) 
	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Dokidoki'/0, l='Test', x=594.60, y=4.00, z=-625.69]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
```

**Comment by Xilef11** [comment]
Fixed for both 1.11.2 and 1.12.
Download from GitHub for now, the builds should be on Curse soon.
[v1.11.2-0.5.1-b1](https://github.com/Xilef11/runesofwizardry-classics/releases/download/v1.11.2-0.5.1-b1/RunesofWizardry-Classics-1.11.2-0.5.1-b1.jar)
[v1.12-0.5.4](https://github.com/Xilef11/runesofwizardry-classics/releases/download/v1.12-0.5.4/RunesofWizardry-Classics-1.12-0.5.4.jar)
